import { readFileSync, writeFileSync, mkdirSync } from "node:fs";

const PT = new URL("../index.html", import.meta.url);
const EN = new URL("../en/index.html", import.meta.url);

const T = [
  ['<html lang="pt-BR">', '<html lang="en">'],
  ['Vinícius Pires da Silva, desenvolvedor C# e .NET, Pleno III na Símix. Uma mesa em pixel art com os projetos que eu construí: Banditboard, Senna, ControlSensors HUD e o Símix Ponto.', 'Vinícius Pires da Silva, C# and .NET developer at Símix. A pixel art desk with the projects I built: Banditboard, Senna, ControlSensors HUD and Símix Ponto.'],
  ['<meta property="og:url" content="https://suiciniv-dev-apps.pages.dev/">', '<meta property="og:url" content="https://suiciniv-dev-apps.pages.dev/en/">'],
  ['Desenvolvedor C# e .NET. Ligue o setup e explore a minha mesa em pixel art: cada aparelho é um projeto.', 'C# and .NET developer. Power on the setup and explore my pixel art desk: every device is a project.'],
  ['<meta property="og:locale" content="pt_BR">\n<meta property="og:locale:alternate" content="en_US">', '<meta property="og:locale" content="en_US">\n<meta property="og:locale:alternate" content="pt_BR">'],
  ['A mesa do Vinícius em pixel art: o celular com o Racco, o monitor do Senna, o HUD e o notebook com o portal da Símix', 'Vinícius\'s desk in pixel art: the phone with Racco, the Senna monitor, the HUD and the laptop with the Símix portal'],
  ['<link rel="canonical" href="https://suiciniv-dev-apps.pages.dev/">', '<link rel="canonical" href="https://suiciniv-dev-apps.pages.dev/en/">'],
  ['"jobTitle":"Desenvolvedor de Software Pleno III"', '"jobTitle":"Software Developer"'],
  ['"url":"https://suiciniv-dev-apps.pages.dev/"', '"url":"https://suiciniv-dev-apps.pages.dev/en/"'],
  ['aria-label="Ligar o setup"', 'aria-label="Power on the setup"'],
  ['Aperte para ligar o setup <span>ou Enter</span>', 'Press to power on the setup <span>or Enter</span>'],
  ['Pular <kbd>Esc</kbd>', 'Skip <kbd>Esc</kbd>'],
  ['aria-label="suiciniv.dev, voltar ao topo"', 'aria-label="suiciniv.dev, back to top"'],
  ['aria-label="Seções"', 'aria-label="Sections"'],
  ['<a href="#mesa">Mesa</a>', '<a href="#mesa">Desk</a>'],
  ['<a href="#projetos">Projetos</a>', '<a href="#projetos">Projects</a>'],
  ['<a href="#espelho">Carreira</a>', '<a href="#espelho">Career</a>'],
  ['<a href="#contato">Contato</a>', '<a href="#contato">Contact</a>'],
  ['<span class="sr"> segredos</span>', '<span class="sr"> secrets</span>'],
  ['aria-label="Tocar uma música lo-fi"', 'aria-label="Play some lo-fi music"'],
  ['<a class="pill pill-sq" href="/en/" hreflang="en" lang="en" id="btnLang" aria-label="English version">EN</a>', '<a class="pill pill-sq" href="/" hreflang="pt-BR" lang="pt-BR" id="btnLang" aria-label="Versão em português">PT</a>'],
  ['<a class="pill pill-cv" href="/assets/Curriculo-Vinicius-Pires-da-Silva.pdf" download>CV', '<a class="pill pill-cv" href="/assets/Resume-Vinicius-Pires-da-Silva.pdf" download>CV'],
  ['<p class="role">Desenvolvedor C# &amp; .NET · Pleno III na Símix</p>', '<p class="role">C# &amp; .NET developer · Mid-level III at Símix</p>'],
  ['aria-label="A minha mesa em pixel art: um celular velho com o Racco na tela, o monitor com o Senna, um segundo monitor com o HUD de sensores, um notebook com o portal da Símix, um quadro de recados, duas prateleiras com a McLaren do Senna, três Funko Pop, um bloco de grama, uma poção, uma miniatura de Mercedes e um chapéu de mago, a Mimi e o Lúcifer, meus gatos, andando pela mesa e pela janela, o Fred debaixo da mesa e eu de costas na cadeira."', 'aria-label="My desk in pixel art: an old phone with Racco on screen, the monitor with Senna, a second monitor with the sensor HUD, a laptop with the Símix portal, a corkboard, two shelves with Senna\'s McLaren, three Funko Pops, a grass block, a potion, a Mercedes miniature and a wizard hat, Mimi and Lucifer, my cats, walking around the desk and the window, Fred the dog under the desk and me in the chair, seen from behind."'],
  ['<span class="so-mouse">Passe o mouse e clique nas coisas da mesa.</span><span class="so-toque">Arraste para os lados e toque nas coisas da mesa.</span> Cada aparelho é um projeto; o resto são segredos.', '<span class="so-mouse">Hover and click things on the desk.</span><span class="so-toque">Swipe sideways and tap things on the desk.</span> Every device is a project; everything else is a secret.'],
  ['Ver projetos <span aria-hidden="true">↓</span>', 'See projects <span aria-hidden="true">↓</span>'],
  ['data-copiar>Copiar e-mail</button>', 'data-copiar>Copy email</button>', true],
  ['aria-label="Objetos da mesa"', 'aria-label="Desk objects"'],
  ['<div><dt>6 anos</dt><dd>na Símix, do suporte a Pleno III</dd></div>', '<div><dt>6 years</dt><dd>at Símix, from support to mid-level III</dd></div>'],
  ['<dd>pull requests aceitos</dd>', '<dd>pull requests merged</dd>'],
  ['<dd>revisões de código</dd>', '<dd>code reviews</dd>'],
  ['<div><dt>1.800+</dt><dd>commits em produção</dd></div>', '<div><dt>1,800+</dt><dd>commits in production</dd></div>'],
  ['<div><dt>2 lojas</dt><dd>Google Play e App Store</dd></div>', '<div><dt>2 stores</dt><dd>Google Play and App Store</dd></div>'],
  ['<h2>Em cima da mesa</h2>', '<h2>On the desk</h2>'],
  ['<p>Cinco coisas que eu construí e uso. Três nasceram no meu tempo livre; duas são da Símix, onde eu trabalho.</p>', '<p>Five things I built and use. Three were born in my free time; two are from Símix, where I work.</p>'],
  ['<p class="sub">Limites do Claude Code e do Antigravity · Android, iPhone, Watch, Windows e Mac</p>', '<p class="sub">Claude Code and Antigravity limits · Android, iPhone, Watch, Windows and Mac</p>'],
  ['<span class="tag tag-me">Projeto pessoal</span>', '<span class="tag tag-me">Side project</span>', true],
  ['<p>Começou num celular Android esquecido na gaveta, que virou um painel sempre ligado na mesa: quanto já foi da sessão de 5 horas e da semana, quando libera e se algum modelo está instável. Hoje também roda no iPhone e no Apple Watch, e vira widget no Windows e no Mac. Cada modelo é o Racco, um guaxinim em pixel art que dorme, sua e estoura conforme o limite chega.</p>', '<p>It started on an Android phone forgotten in a drawer, which became an always-on panel on the desk: how much of the 5-hour session and the week is used, when it resets and whether any model is unstable. Today it also runs on iPhone and Apple Watch, and becomes a widget on Windows and Mac. Each model is Racco, a pixel art raccoon that sleeps, sweats and bursts as the limit gets close.</p>'],
  ['<p>Kotlin com Jetpack Compose no Android e Compose Desktop no Windows. O uso vem do próprio Claude Code no PC, por um hook que roda o <code>/usage</code>, sem token no celular; a chave de pareamento fica cifrada com AES-256-GCM e Android Keystore. Código aberto, com site e documentação em português e inglês.</p>', '<p>Kotlin with Jetpack Compose on Android and Compose Desktop on Windows. Usage comes from Claude Code itself on the PC, through a hook that runs <code>/usage</code>, with no token on the phone; the pairing key is encrypted with AES-256-GCM and the Android Keystore. Open source, with a website and docs in Portuguese and English.</p>'],
  ['Conhecer e baixar <span aria-hidden="true">↗</span>', 'Learn more and download <span aria-hidden="true">↗</span>'],
  ['Ver código <span aria-hidden="true">↗</span>', 'View code <span aria-hidden="true">↗</span>', true],
  ['<p class="fine">grátis e de código aberto (MIT) · projeto pessoal, sem vínculo com a Anthropic</p>', '<p class="fine">free and open source (MIT) · side project, not affiliated with Anthropic</p>'],
  ['aria-label="Tela do Banditboard: sessão e semana em cima e os quatro Raccos com a barra de cada modelo"', 'aria-label="Banditboard screen: session and week on top and the four Raccos with each model\'s bar"'],
  ['data-cena="normal" data-ativo="1">dia normal</button>', 'data-cena="normal" data-ativo="1">normal day</button>'],
  ['data-cena="dormindo">sessão zerada</button>', 'data-cena="dormindo">session at zero</button>'],
  ['data-cena="suando">semana em 88%</button>', 'data-cena="suando">week at 88%</button>'],
  ['data-cena="vermelho">semana em 97%</button>', 'data-cena="vermelho">week at 97%</button>'],
  ['data-cena="esgotado">limite em 100%</button>', 'data-cena="esgotado">limit at 100%</button>'],
  ['data-cena="fable">só o Fable no limite</button>', 'data-cena="fable">only Fable at the limit</button>'],
  ['<p class="sub">O assistente do meu Windows · C# e WinUI 3</p>', '<p class="sub">My Windows assistant · C# and WinUI 3</p>'],
  ['<p><b>Trabalha calado.</b> Feito em C# com WinUI 3, mostra um painel do dia e manda avisos do Windows quando chega PR para revisar, issue nova, merge, reunião, lembrete, chuva ou limite do Claude. E guarda a memória: o Claude Code grava ali as decisões, os motivos e onde parou, e lê tudo de volta na sessão seguinte.</p>', '<p><b>It works quietly.</b> Built in C# with WinUI 3, it shows a daily panel and sends Windows notifications for PRs to review, new issues, merges, meetings, reminders, rain and Claude limits. And it keeps the memory: Claude Code saves decisions, reasons and where it stopped, and reads it all back in the next session.</p>'],
  ['<li>API local</li>', '<li>Local API</li>'],
  ['<p class="note"><b>Sem download.</b> Foi feito para uma máquina só, a minha. Está aqui como construção, não como produto.</p>', '<p class="note"><b>No download.</b> It was made for a single machine: mine. It\'s here as a build, not as a product.</p>'],
  ['aria-label="Simulação do Senna"', 'aria-label="Senna simulation"'],
  ['<p class="demo-cap">Uma simulação do Senna, com dados de exemplo. Arraste os nós do mapa, troque de tela na barra lateral e desligue avisos nos ajustes: o dia passa e ele só fala o que você deixou.</p>', '<p class="demo-cap">A simulation of Senna with sample data. Drag the map nodes, switch screens in the sidebar and turn alerts off in the settings: the day goes by and it only speaks up about what you allowed.</p>'],
  ['<p class="sub">HUD de sensores · Windows</p>', '<p class="sub">Sensor HUD · Windows</p>'],
  ['<span class="tag tag-me">Código aberto</span>', '<span class="tag tag-me">Open source</span>'],
  ['<p>Um HUD de monitoramento em tempo real para telas secundárias e gabinetes: CPU, GPU, memória, armazenamento, clima e áudio, direto do Windows. É o que fica no monitor do lado enquanto eu trabalho.</p>', '<p>A real-time monitoring HUD for secondary screens and PC cases: CPU, GPU, memory, storage, weather and audio, straight from Windows. It\'s what sits on the side monitor while I work.</p>'],
  ['<li>Sensores de hardware</li>', '<li>Hardware sensors</li>'],
  ['Baixar <span aria-hidden="true">↓</span>', 'Download <span aria-hidden="true">↓</span>'],
  ['<p class="fine">Windows 10 e 11 · grátis e de código aberto</p>', '<p class="fine">Windows 10 and 11 · free and open source</p>'],
  ['aria-label="Painel do ControlSensors com CPU, GPU, memória, disco, clima e áudio"', 'aria-label="ControlSensors panel with CPU, GPU, memory, disk, weather and audio"'],
  ['id="hudReboot">reiniciar</button>', 'id="hudReboot">restart</button>'],
  ['<p class="sub">App de ponto · Android, iOS e Windows</p>', '<p class="sub">Time clock app · Android, iOS and Windows</p>'],
  ['<span class="tag tag-work">Símix · trabalho</span>', '<span class="tag tag-work">Símix · work</span>', true],
  ['<p>O app de registro de ponto do ecossistema Símix Ponto: online e offline com sincronização, GPS e cerca geográfica, reconhecimento facial com Azure Face, biometria, modo quiosque e proteção contra localização falsa. Tem módulo para motoristas e conversa com sistemas legados, como o PcPonto.</p>', '<p>The time clock app of the Símix Ponto ecosystem: online and offline with sync, GPS and geofencing, face recognition with Azure Face, biometrics, kiosk mode and protection against fake locations. It has a module for drivers and talks to legacy systems such as PcPonto.</p>'],
  ['<h4>Minha parte</h4>', '<h4>My part</h4>', true],
  ['<li>Responsável pela versão iOS e pela publicação na App Store.</li>', '<li>Owner of the iOS version and the App Store release.</li>'],
  ['<li>Publicação automática na Google Play, TestFlight e Microsoft Store pelo GitHub Actions, com versão automática.</li>', '<li>Automated releases to Google Play, TestFlight and the Microsoft Store with GitHub Actions, with automatic versioning.</li>'],
  ['<li>Liderei a integração da verificação facial, com validação e testes.</li>', '<li>Led the face verification integration, including validation and tests.</li>'],
  ['<li>Escrevi a maior parte do cliente da API usado pelo app (Refit, Polly), publicado como pacote NuGet.</li>', '<li>Wrote most of the API client used by the app (Refit, Polly), published as a NuGet package.</li>'],
  ['<b>Visitante</b>', '<b>Visitor</b>'],
  ['<small>Horário atual</small>', '<small>Current time</small>'],
  ['<small>Localização</small>', '<small>Location</small>'],
  ['</svg>Observação</div>', '</svg>Note</div>'],
  ['data-tipo="RHO">Home Office</button>', 'data-tipo="RHO">Home office</button>'],
  ['data-tipo="RSE">Serviço externo</button>', 'data-tipo="RSE">Field service</button>'],
  ['<b>Registros de hoje <em id="mpQtd">3</em></b><small>Toque em um registro para visualizar</small>', '<b>Today\'s punches <em id="mpQtd">3</em></b><small>Tap a punch to view it</small>'],
  ['</svg>Usuários</span>', '</svg>Users</span>'],
  ['</svg>Registro</span>', '</svg>Clock in</span>'],
  ['</svg>Painel</span>', '</svg>Dashboard</span>'],
  ['</svg>Consulta</span>', '</svg>Lookup</span>'],
  ['</svg>Config</span>', '</svg>Settings</span>'],
  ['aria-live="polite">Verificando o rosto…</p>', 'aria-live="polite">Checking face…</p>'],
  ['<p class="demo-cap">Uma simulação do app. Toque em Home Office ou Serviço externo; toque em Online para ficar sem internet: o ponto fica no aparelho e sobe quando a rede volta.</p>', '<p class="demo-cap">A simulation of the app. Tap Home office or Field service; tap Online to go offline: the punch stays on the device and uploads when the network is back.</p>'],
  ['<p class="sub">Plataforma web · SaaS multitenant</p>', '<p class="sub">Web platform · multitenant SaaS</p>'],
  ['<p>A plataforma na nuvem por trás do app e dos relógios de ponto: gestão de jornada para empresas de vários segmentos, do supermercado à transportadora. Automatiza o registro de jornada, as escalas e folgas e o banco de horas, com portal do gestor e portal do colaborador, e integra com relógios homologados e com os principais sistemas de folha.</p>', '<p>The cloud platform behind the app and the time clocks: workforce time management for companies in many industries, from supermarkets to trucking. It automates time tracking, schedules and days off and the hour bank, with a manager portal and an employee portal, and integrates with certified time clocks and the main payroll systems.</p>'],
  ['<li>Faço parte do time que desenvolve a plataforma, do backend à interface.</li>', '<li>I\'m part of the team that builds the platform, from backend to UI.</li>'],
  ['<li>Liderei a migração do front-end de Blazor Server para WebAssembly: o pacote caiu de 39 MB para 16 MB.</li>', '<li>Led the front-end migration from Blazor Server to WebAssembly: the bundle went from 39 MB to 16 MB.</li>'],
  ['<li>Espelho de ponto com PDF e assinatura eletrônica, exportação para folha, aprovações em lote e ponto offline com PWA.</li>', '<li>Timesheets with PDF and electronic signature, payroll export, bulk approvals and offline clock-in with a PWA.</li>'],
  ['<li>Testes automatizados com xUnit e Playwright, que rodam a cada deploy.</li>', '<li>Automated tests with xUnit and Playwright that run on every deploy.</li>'],
  ['Conhecer o produto <span aria-hidden="true">↗</span>', 'See the product <span aria-hidden="true">↗</span>'],
  ['aria-label="Simulação do portal Símix Ponto Cloud"', 'aria-label="Símix Ponto Cloud portal simulation"'],
  ['<p class="demo-cap">Uma simulação do portal, com empresas e pessoas inventadas. Troque de empresa no topo, navegue pelo menu e recolha os cartões. O ponto que você bater no app ali em cima chega aqui.</p>', '<p class="demo-cap">A simulation of the portal, with made-up companies and people. Switch companies at the top, browse the menu and collapse the cards. The punch you clock on the app above shows up here.</p>'],
  ['<a href="#arcanista">Arcanista</a>', '<a href="#arcanista">Arcanist</a>'],
  ['<h2>O Arcanista</h2>', '<h2>The Arcanist</h2>'],
  ['<p>Do estágio no suporte ao Pleno III, um degrau por vez, na mesma casa desde 2020.</p>', '<p>From a support internship to mid-level III, one step at a time, at the same company since 2020.</p>'],
  ['aria-label="Eu em pixel art: cabelo escuro, óculos redondos, barba e moletom cinza"', 'aria-label="Me in pixel art: dark hair, round glasses, beard and a grey hoodie"'],
  ['<div><dt>Classe</dt><dd>Arcanista III</dd></div>', '<div><dt>Class</dt><dd>Arcanist III</dd></div>'],
  ['<div><dt>Nível</dt><dd>Pleno III</dd></div>', '<div><dt>Level</dt><dd>Mid-level III</dd></div>'],
  ['<div><dt>Guilda</dt><dd>Símix Sistemas</dd></div>', '<div><dt>Guild</dt><dd>Símix Sistemas</dd></div>'],
  ['<div><dt>Origem</dt><dd>Canoas, RS</dd></div>', '<div><dt>Origin</dt><dd>Canoas, Brazil</dd></div>'],
  ['<h3>Trilha do mago</h3>', '<h3>The mage\'s path</h3>'],
  ['<p>Cada cargo, uma classe. Daqui para a frente está trancado.</p>', '<p>Each role, a class. From here on it\'s locked.</p>'],
  ['<b>Aprendiz</b><span>2020 · estágio no suporte</span>', '<b>Apprentice</b><span>2020 · support intern</span>'],
  ['<b>Iniciado</b><span>2021 · qualidade</span>', '<b>Initiate</b><span>2021 · QA</span>'],
  ['<b>Adepto</b><span>2021 · implantação</span>', '<b>Adept</b><span>2021 · deployment</span>'],
  ['<b>Mago</b><span>2023 · desenvolvedor júnior</span>', '<b>Mage</b><span>2023 · junior developer</span>'],
  ['<b>Arcanista III</b><span>2024 → hoje · Pleno I, II e III</span>', '<b>Arcanist III</b><span>2024 → now · mid-level I, II and III</span>'],
  ['<b>Arquimago</b>', '<b>Archmage</b>'],
  ['<b>Mestre Arcano</b>', '<b>Arcane Master</b>'],
  ['<b>Grão-Mago</b>', '<b>Grand Mage</b>'],
  ['<b>Mago Supremo</b>', '<b>Supreme Mage</b>'],
  ['<span>trancado</span>', '<span>locked</span>', true],
  ['<p class="lead">Sou desenvolvedor C# e .NET, Pleno III na Símix Sistemas. Entrei em 2020 como estagiário de suporte, configurando relógio de ponto, e cheguei aqui aprendendo sozinho, direto da documentação e da prática.</p>', '<p class="lead">I\'m a C# and .NET developer at Símix Sistemas. I joined in 2020 as a support intern, setting up time clocks, and got here self-taught, straight from the docs and practice.</p>'],
  ['<p>Trabalho do banco de dados à interface no Símix Ponto Cloud, uma plataforma SaaS multitenant feita com ABP Framework, Blazor, PostgreSQL e Azure, e no app Símix Ponto em .NET MAUI, publicado na Google Play e na App Store. Liderei a migração do front-end para Blazor WebAssembly, automatizei a publicação do app nas lojas e participei da migração do sistema legado em VB6 para .NET.</p>', '<p>I work from the database to the UI on Símix Ponto Cloud, a multitenant SaaS platform built with ABP Framework, Blazor, PostgreSQL and Azure, and on the Símix Ponto app in .NET MAUI, published on Google Play and the App Store. I led the front-end migration to Blazor WebAssembly, automated the app\'s store releases and took part in migrating the legacy VB6 system to .NET.</p>'],
  ['<p>Gosto de performance, de testes automatizados e de automatizar o que se repete. No meu tempo livre, construo as ferramentas que eu mesmo uso.</p>', '<p>I like performance, automated tests and automating whatever repeats. In my free time, I build the tools I use myself.</p>'],
  ['<span class="perk-k">Habilidade especial</span><p>Algumas ideias são úteis. Outras… eu só queria ver funcionando.</p>', '<span class="perk-k">Special move</span><p>Some ideas are useful. Others… I just wanted to see them working.</p>'],
  ['<span class="perk-k">Passiva · Autodidata</span><p>Aprendi pela documentação oficial e pela prática, com foco em Clean Code, SOLID e Design Patterns.</p>', '<span class="perk-k">Passive · Self-taught</span><p>Learned from the official docs and practice, focused on Clean Code, SOLID and Design Patterns.</p>'],
  ['<h3>Inventário</h3>', '<h3>Inventory</h3>'],
  ['<p>Passe o mouse ou toque num item.</p>', '<p>Hover or tap an item.</p>'],
  ['<h2>Espelho de ponto</h2>', '<h2>Timesheet</h2>'],
  ['<p>Seis anos batendo ponto na mesma empresa, do suporte ao Pleno III. As linhas em coral são do meu tempo livre.</p>', '<p>Six years clocking in at the same company, from support to mid-level III. Coral rows are from my free time.</p>'],
  ['<div><span>Espelho de ponto</span><b>Vinícius Pires da Silva</b></div>', '<div><span>Timesheet</span><b>Vinícius Pires da Silva</b></div>'],
  ['<div><span>Empresa</span><b>Símix Sistemas · Canoas, RS</b></div>', '<div><span>Company</span><b>Símix Sistemas · Canoas, Brazil</b></div>'],
  ['<div><span>Período</span><b>01/2020 a hoje</b></div>', '<div><span>Period</span><b>01/2020 to now</b></div>'],
  ['<th scope="col">Data</th><th scope="col">Marcação</th><th scope="col">Ocorrência</th><th scope="col">Observação</th>', '<th scope="col">Date</th><th scope="col">Punch</th><th scope="col">Event</th><th scope="col">Notes</th>'],
  ['<i>E</i>', '<i>IN</i>', true],
  ['<i>livre</i>', '<i>free</i>', true],
  ['<td>Estágio em suporte N1</td><td>Atendimento, redes e configuração de relógios de ponto biométricos. Foi aqui que eu bati o primeiro ponto.</td>', '<td>Tier 1 support intern</td><td>Customer support, networking and setting up biometric time clocks. This is where I clocked in for the first time.</td>'],
  ['<td>Qualidade e implantação</td><td>Homologação de versões, testes antes da entrega e implantação com uso intenso de SQL Server.</td>', '<td>QA and deployment</td><td>Release validation, testing before delivery and SQL Server-heavy deployments.</td>'],
  ['<td>Desenvolvedor Júnior</td><td>Relatórios, motor de cálculo e a migração do legado em VB6 para .NET. Em outubro, o app em .NET MAUI.</td>', '<td>Junior developer</td><td>Reports, the calculation engine and the VB6-to-.NET legacy migration. In October, the .NET MAUI app.</td>'],
  ['<td>Pleno I</td><td>Em novembro, a plataforma Símix Ponto Cloud, do backend à interface.</td>', '<td>Mid-level I</td><td>In November, the Símix Ponto Cloud platform, backend to UI.</td>'],
  ['<td>Pleno II</td><td>Mais revisão de código, mais testes e a publicação nas lojas no automático.</td>', '<td>Mid-level II</td><td>More code review, more tests and store releases on autopilot.</td>'],
  ['<td>Pleno III</td><td>Hoje.</td>', '<td>Mid-level III</td><td>Today.</td>'],
  ['<td>Tempo livre: um HUD de sensores, de código aberto.</td>', '<td>Free time: an open source sensor HUD.</td>'],
  ['<td>Tempo livre: o celular da gaveta virou painel. Agora tem até iPhone e Apple Watch.</td>', '<td>Free time: the phone in the drawer became a panel. It even has iPhone and Apple Watch now.</td>'],
  ['<td>Tempo livre: de Python para C#, e de 682 MB para leve.</td>', '<td>Free time: from Python to C#, and from 682 MB to lightweight.</td>'],
  ['<div class="banco"><span>Banco de horas</span><b>+6 anos e contando</b></div>', '<div class="banco"><span>Hour bank</span><b>+6 years and counting</b></div>'],
  ['<span class="carimbo">Assinado eletronicamente</span>', '<span class="carimbo">Electronically signed</span>'],
  ['<small>A assinatura eletrônica do espelho de ponto é uma das coisas que eu fiz na Símix.</small>', '<small>Electronic timesheet signing is one of the things I built at Símix.</small>'],
  ['<h2>Bora conversar?</h2>', '<h2>Let\'s talk?</h2>'],
  ['<p>Estou sempre aberto a trocar ideias sobre tecnologia, arquitetura de software ou novas oportunidades.</p>', '<p>I\'m always open to chat about technology, software architecture or new opportunities.</p>'],
  ['Ol%C3%A1%2C%20Vin%C3%ADcius%21%20Vi%20o%20seu%20portf%C3%B3lio%20e%20queria%20trocar%20uma%20ideia.', 'Hi%20Vin%C3%ADcius%2C%20I%20saw%20your%20portfolio%20and%20would%20like%20to%20talk.'],
  ['>Chamar no WhatsApp</a>', '>Message on WhatsApp</a>'],
  ['>Mandar um e-mail</a>', '>Send an email</a>'],
  ['GitHub pessoal <span', 'Personal GitHub <span'],
  ['GitHub da Símix <span', 'Símix GitHub <span'],
  ['<li><a href="/assets/Curriculo-Vinicius-Pires-da-Silva.pdf" download>Currículo em PDF <span aria-hidden="true">↓</span></a></li>\n              <li><a href="/assets/Resume-Vinicius-Pires-da-Silva.pdf" download hreflang="en" lang="en">Résumé in English <span aria-hidden="true">↓</span></a></li>', '<li><a href="/assets/Resume-Vinicius-Pires-da-Silva.pdf" download>Résumé (PDF) <span aria-hidden="true">↓</span></a></li>\n              <li><a href="/assets/Curriculo-Vinicius-Pires-da-Silva.pdf" download hreflang="pt-BR" lang="pt-BR">Currículo em português <span aria-hidden="true">↓</span></a></li>'],
  ['placeholder="digite ajuda"', 'placeholder="type help"'],
  ['<button type="button" data-cmd="ajuda">ajuda</button>\n              <button type="button" data-cmd="projetos">projetos</button>\n              <button type="button" data-cmd="contato">contato</button>\n              <button type="button" data-cmd="segredos">segredos</button>', '<button type="button" data-cmd="help">help</button>\n              <button type="button" data-cmd="projects">projects</button>\n              <button type="button" data-cmd="contact">contact</button>\n              <button type="button" data-cmd="secrets">secrets</button>'],
  ['<span>Construído bloco a bloco, sem framework. © 2026</span>', '<span>Built block by block, no framework. © 2026</span>'],
  ['voltar ao topo <span aria-hidden="true">↑</span>', 'back to top <span aria-hidden="true">↑</span>'],
  ['<h2 id="conqTitulo">Segredos</h2>', '<h2 id="conqTitulo">Secrets</h2>'],
  ['aria-label="Fechar"', 'aria-label="Close"'],
  ['id="conqReset">zerar o progresso</button>', 'id="conqReset">reset progress</button>']
];

let html = readFileSync(PT, "utf8");
const faltou = [];
for (const [pt, en, todas] of T) {
  if (!html.includes(pt)) { faltou.push(pt); continue; }
  html = todas ? html.split(pt).join(en) : html.replace(pt, en);
}
if (faltou.length) {
  console.error("Trechos do index.html sem tradução (o texto em português mudou?):\n- " + faltou.map(s => s.slice(0, 90)).join("\n- "));
  process.exit(1);
}
mkdirSync(new URL("../en/", import.meta.url), { recursive: true });
writeFileSync(EN, html);
console.log("en/index.html gerado");
